error: rename to undefined
This is a minor change to rename the error drv to undefined drv. This is
because the explicit purpose is to raise a 'special' error when a
control is *by design* undefined.

BUG=None
TEST=sudo servod // get's triggered quite a bit on startup

Change-Id: Ie01a94f9d9d0a9d8a2a9b05072a45e40abac048f
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/hdctools/+/3218528
Reviewed-by: Brian Nemec <bnemec@chromium.org>
Tested-by: Ruben Rodriguez Buchillon <coconutruben@chromium.org>
Commit-Queue: Ruben Rodriguez Buchillon <coconutruben@chromium.org>