drv: introduce fast_ec
This is an expansion on simple_ec to also try and match known error
strings. This speeds up failures as the system doesn't wait for 3s for a
timeout but matches a known error right away.

BUG=b:180668060,b:180670934

// both tests are done by changing 'vers' to 'vors' inside ec_info.xml
// This is to generate an error on the EC console.
TEST=sudo servod -b scarlet // 'vors' through 'fast_ec'
     time dut-control ec_board
Problem with ['ec_board'] :: Failed to retrieve output for 'vors'
matching regex 'RO:\\s+(\\S*)_v?[\\d.\\w-]+[\\n\\r]'. EC: Timeout waiting
for response. There was output: , > chan save, > , > chan 1, > , > vors,
Command 'vors' not found or ambiguous., >

real    0m3.260s //3.2s to fail
user    0m0.136s
sys     0m0.052s

TEST=sudo servod -b scarlet // 'vors' through 'fast_ec'
     time dut-control ec_board
Problem with ['ec_board'] :: Failed to retrieve output for 'vors'
matching regex 'RO:\\s+(\\S*)_v?[\\d.\\w-]+[\\n\\r]'. Ran into cros ec
error: u"Command 'vors' not found or ambiguous."

real    0m0.388s //~0.4s to fail
user    0m0.124s
sys     0m0.076s

Change-Id: I7f62bc53122a62388a264ea48b590f82897b5103
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/hdctools/+/2708762
Reviewed-by: Brian Nemec <bnemec@chromium.org>
Commit-Queue: Ruben Rodriguez Buchillon <coconutruben@chromium.org>
Tested-by: Ruben Rodriguez Buchillon <coconutruben@chromium.org>