servo_adcs_enabled: accomodate c2d2 + ccd
In this scenario, we have a redefinition of the control. This is an
issue, since ccd would overwrite the c2d2 definition (sequencing) but we
need the c2d2 definition. The solution is to treat the c2d2 definition
as a special case, so ccd cannot overwrite it.

BUG=None
TEST=sudo servod -b guybrush -c guybrush_p0.xml &
     dut-power --vbat-rate 0 -t 3

// symptom without this CL
TEST=sudo servod -b guybrush -c guybrush_p0.xml &

[...]
servo.system_config.SystemConfigError: Duplicate control
servo_adcs_enabled without 'clobber_ok' key
[...]

Change-Id: I106d1920cd3807a0e7fe3041414f9b24a126d2c1
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/hdctools/+/3046561
Tested-by: Ruben Rodriguez Buchillon <coconutruben@chromium.org>
Reviewed-by: Furquan Shaikh <furquan@chromium.org>
Commit-Queue: Ruben Rodriguez Buchillon <coconutruben@chromium.org>