servod: Fail if invalid aliases
Check that aliases have only legal characters to catch missing commas
or extra whitespace.

After this change servod fails on start with the error :
servo.system_config.SystemConfigError: file '/usr/lib64/python3.6/site-packages/servo/data/cr50.xml' control element 'ec3po_gsc_uart' invalid alias "usbpd_uart_pty
    gsc_uart_pty"

BUG=None
TEST=cros_workon --host start hdctools
TEST=sudo emerge hdctools
TEST=sudo servod

Change-Id: I4ee204540f3a9e4ddde0feca6f50ec0655855317
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/hdctools/+/4412677
Commit-Queue: Jeremy Bettis <jbettis@chromium.org>
Tested-by: Jeremy Bettis <jbettis@chromium.org>
Reviewed-by: 488603086791@cloudbuild.gserviceaccount.com <488603086791@cloudbuild.gserviceaccount.com>
Reviewed-by: Matthew Blecker <matthewb@chromium.org>