python3: relative imports
in py3 the directory of the module file is no longer in the path
(always) so e.g.
`import tool`
you have to use
`from . import tool`

This change fixes those imports

Lastly, the change also modifies scripts/servoflex_test_v2.py by
removing the unnecessary import. While it's true that it's better to
have one source of truth, two static PIDs do not justify the acrobatics
of changing import paths especially as it's otherwise a standalone
script.

script used in sub directories to auto-fix as much as possible:

for w in $(grep -hr import | sort | uniq | sed "s/import //g"); do [[ -f
$w.py ]] && sed -i "s/^import $w/from . import $w/g" *.py; done

scripts used to validate and and check all remaining import statements

grep -hEr "from [^.].+ import"  servo/drv/ servo/utils/ servo/interface/
servo/tools/ servo/data/

grep -hEr "^import"  servo/drv/ servo/utils/ servo/interface/
servo/tools/

BUG=chromium:999878,b:173654723
TEST=manual testing
     scripts above

// before change
TEST=python3 /usr/lib64/python3.6/site-packages/servo/servod.py
    import bbadc
ModuleNotFoundError: No module named 'bbadc'

// after change
TEST=python3 /usr/lib64/python3.6/site-packages/servo/servod.py

Change-Id: I44d15231738d3a605cc189bec7836b1729a18874
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/hdctools/+/2125085
Tested-by: Ruben Rodriguez Buchillon <coconutruben@chromium.org>
Commit-Queue: Ruben Rodriguez Buchillon <coconutruben@chromium.org>
Reviewed-by: Matthew Blecker <matthewb@chromium.org>